sudo: required
language: python
python:
- '2.7'
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- python bot/bot.py
before_install:
- openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv
  -in .security.tar.gz.enc -out ~/security.tar.gz -d
- tar zxf ~/security.tar.gz -C ~
- export GITHUB_TOKEN=$( cat ~/security/token )
